### ISSUE TITLE
Status on this project?

### ISSUE THREAD

**Issue by garbles** [baconjs/bacon.model#17]
I've noticed that the last commit was almost over 3 months ago, so I'm curious about your outlook on this project. Is there a reason that it hasn't been updated? Are you looking for help to maintain it?

Thanks!

**Comment by raimohanska** [comment]
Hi, I'm not really maintaining this right now as I have no personal interest in it and no-one is paying me to, either :)

I'll gladly include anyone with at least one merged pull request in the contributors team.

So, yes, contribution is very welcome!

**Comment by garbles** [comment]
Cool. Thanks for the update. I am interested in contributing, so hopefully I will submit a PR within a few days.
